### ISSUE TITLE
Grammar Selector Duplicate

### ISSUE THREAD

**Issue by TheNameKevinWasTaken** [13xforever/language-x86_64-assembly#1]
When using the grammar switcher (default Ctrl+Shift+L) "x86 and x86_64 Assembly" shows up as an option twice with no noticeable difference. Not sure if this is a problem on my end, the packages end, or atoms end.

[example photo](https://cloud.githubusercontent.com/assets/16211858/15119979/42c06e28-15c8-11e6-8571-ed2f68b6398c.png)

**Comment by 13xforever** [comment]
Should be fixed now

**Comment by TheNameKevinWasTaken** [comment]
Works on my end, thanks.
