### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by shark-oxi** [13xforever/language-x86_64-assembly#2]
Hi,

The package is impossible to uninstall

```
Uninstalling “language-x86-64-assembly” failed.Hide output…
Failed to delete language-x86-64-assembly: Does not exist
```

Best regards,

**Comment by 13xforever** [comment]
It was a change in how Atom handles the package filenames (probably on Windows only). Despite the error, it should in fact uninstall.

You can check it at `%userprofile%\.atom\packages` (or `~\.arom`)

**Comment by shark-oxi** [comment]
It does the same with other package, I just restarted Atom and the package was effectively uninstalled.

In fact it's because Atom  seems to try uninstalling twice, failing the second time because it isn't there any more. It's a known [issue](https://github.com/atom/atom/issues/11464).
