### ISSUE TITLE
Comment dont work property

### ISSUE THREAD

**Issue by meron1122** [13xforever/language-x86_64-assembly#4]
I used nasm compiler, co comment is like this
``
;comment
``

If i use keyboard <kbd>ctrl</kbd> + <kbd>/</kbd> this comment like this:
``
/* comment */
``

Which is invalid.

**Comment by 13xforever** [comment]
BTW, this is a syntax highlighter, not a full-fledged language service. Editors _do_ infer some language properties from syntax definitions, but it's in no way a complete package, and it is expected that some things will not work.

**Comment by meron1122** [comment]
I solved this, check PR tab ;)
